### ISSUE TITLE
general help

### ISSUE THREAD

**Issue by BenRaschke** [joshbuddy/swearjar#20]
@joshbuddy - thank you for creating and sharing this repo!  I hope to contribute as well.  Do you have any additional directions for setting up and running this?  I have cloned the repo and have Ruby setup...

**Comment by m1foley** [comment]
There are no instructions other than the [README](https://github.com/joshbuddy/swearjar#usage). You can see more usage examples in the [specs](https://github.com/joshbuddy/swearjar/tree/master/spec).

**Comment by m1foley** [comment]
The README should have contribution instructions, so I've created [an issue](https://github.com/joshbuddy/swearjar/issues/21)  to add them.

Contributions are welcome:
1. Add a new spec for the feature if appropriate
2. Run `bundle exec rake` to run the specs
3. Create a Pull Request in the GitHub repo

Thanks for reaching out!
